
services:
  pg-master:
    image: postgres:15
    container_name: pg-master
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c wal_level=replica
      -c max_wal_senders=10
      -c hot_standby=on

  pg-replica:
    image: postgres:15
    container_name: pg-replica
    depends_on:
      - pg-master
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg-replica-data:/var/lib/postgresql/data
    command: >
      bash -c "
      until pg_isready -h pg-master -p 5432; do sleep 2; done &&
      rm -rf /var/lib/postgresql/data/* &&
      pg_basebackup -h pg-master -U postgres -D /var/lib/postgresql/data -Fp -Xs -P -R &&
      exec docker-entrypoint.sh postgres
      "

volumes:
  pg-master-data:
  pg-replica-data:
